# Yeh code codemagic.yaml file mein paste karein
workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
    
    scripts:
      - name: Install dependencies
        script: flutter packages pub get
        
      - name: Build Android App
        script: flutter build apk --release
        
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
