name: beta_panel_app
description: A new Flutter project for monitoring.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase ke liye zaroori packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  
  # Location ke liye package
  location: ^5.0.3
  
  # Background mein kaam karne ke liye (baad mein istemal hoga)
  background_fetch: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
